
import type { Metadata } from "next";
import { BackgroundEffects } from "@/components/ui/background-effects";
import { MouseFollower } from "@/components/ui/mouse-follower";
import { Navbar } from "@/components/Shared/navbar";
import Footer from "@/components/Shared/footer";




export const metadata: Metadata = {
  title: "SaibonSoft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   
      <>
        <MouseFollower />
        <BackgroundEffects />
        <Navbar />
        <div className="bg-gray-900"> {children}</div>
        <Footer />
      </>

  );
}
