export const projects = [
    {
      title: "E-Commerce Platform",
      description: "A modern e-commerce solution with real-time inventory management.",
      image: "https://images.unsplash.com/photo-1661956602116-aa6865609028?auto=format&fit=crop&q=80&w=800",
      tags: ["Next.js", "TypeScript", "Tailwind"],
      link: "https://example.com/ecommerce",
      category: "Web Apps",
    },
    {
      title: "Healthcare App",
      description: "Mobile application for patient care management and scheduling.",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800",
      tags: ["React Native", "Node.js", "MongoDB"],
      link: "https://example.com/healthcare",
      category: "Web Apps",
    },
    {
      title: "Healthcare App",
      description: "Mobile application for patient care management and scheduling.",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800",
      tags: ["React Native", "Node.js", "MongoDB"],
      link: "https://example.com/healthcare",
      category: "Graphics",
    },
    {
      title: "Healthcare App",
      description: "Mobile application for patient care management and scheduling.",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800",
      tags: ["React Native", "Node.js", "MongoDB"],
      link: "https://example.com/healthcare",
      category: "Web Development",
    },
    {
      title: "Healthcare App",
      description: "Mobile application for patient care management and scheduling.",
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800",
      tags: ["React Native", "Node.js", "MongoDB"],
      link: "https://example.com/healthcare",
      category: "Web Development",
    },
  ];